// AUTO-GENERATED by build-manifest.mjs — DO NOT EDIT BY HAND.
// 改动需求改 build-manifest.mjs,然后重跑 `node build-manifest.mjs`。
const MANIFEST = [
  {
    "name": "Creation-list.inline.html",
    "displayName": "Creation-list",
    "html": "灵翼/V1.1/Creation-list.inline.html",
    "htmlBasename": "Creation-list.inline.html",
    "md": "灵翼/V1.1/vibe-coding.md",
    "mdBasename": "vibe-coding.md",
    "dir": "灵翼/V1.1",
    "size": 1369356,
    "sizeStr": "1.3MB",
    "mtime": 1782354293,
    "mtimeStr": "06-25 10:24",
    "group": "",
    "inline": true,
    "system": "灵翼",
    "version": "V1.1"
  }
];
const SYSTEMS = ["灵翼"];
const VERSIONS_BY_SYSTEM = {
  "灵翼": [
    "V1.1"
  ]
};
const DEFAULT_BUCKET = {"system":"灵翼","version":"v1.0"};
