// AUTO-GENERATED by build-manifest.mjs — DO NOT EDIT BY HAND.
// 改动需求改 build-manifest.mjs,然后重跑 `node build-manifest.mjs`。
const MANIFEST = [
  {
    "name": "workbench.inline.html",
    "displayName": "workbench",
    "html": "掌视/v1.1/workbench.inline.html",
    "htmlBasename": "workbench.inline.html",
    "md": "掌视/v1.1/vibe-coding.md",
    "mdBasename": "vibe-coding.md",
    "dir": "掌视/v1.1",
    "size": 5487701,
    "sizeStr": "5.2MB",
    "mtime": 1782540306,
    "mtimeStr": "06-27 14:05",
    "group": "",
    "inline": true,
    "system": "掌视",
    "version": "v1.1"
  }
];
const SYSTEMS = ["掌视"];
const VERSIONS_BY_SYSTEM = {
  "掌视": [
    "v1.1"
  ]
};
const DEFAULT_BUCKET = {"system":"掌视","version":"v1.0"};
